#!/usr/bin/env python
# This script converts quadgrams in the format "KEY COUNT"
# To the format "LOG_PROBABILITY"

import math

ngrams = {}
with open('./english_quadgrams.txt', 'r') as f:
    for line in f:
        key, count = line.strip().split(' ')
        ngrams[key] = count

    n = sum([ int(x) for x in ngrams.values() ])
    for key in ngrams.keys():
        ngrams[key] = math.log10(float(ngrams[key]) / n)
    floor = math.log10(0.01 / n)

    for i in range(65, 91):
        for j in range(65, 91):
            for k in range(65, 91):
                for l in range(65, 91):
                    quad = f"{chr(i)}{chr(j)}{chr(k)}{chr(l)}"
                    if quad in ngrams:
                        print(ngrams[quad])
                    else:
                        print(floor)
